language: objective-c
osx_image: xcode63

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - SCRIPT="xctool -project Spot.xcodeproj -scheme Spot -sdk iphonesimulator8.3 test"

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script: $SCRIPT

notifications:
  email: false
